STATIC_DIR_FOR_CSV_FILES = 'static\\data\\'
FILE_GENRE_TITLE = STATIC_DIR_FOR_CSV_FILES + 'genre_title.csv'

LENGTH_TEXT = 254
LENGTH_USERNAME = 150
LENGTH_DISCRIPTION = 256
LENGTH_ROLE = 50
LENGTH_SHOW_NAME = 20

CHOICES_SCORE = ((score, score) for score in range(11))

USERNAME_RESTRICTION = 'me'

ADDITIONAL_USER_FIELDS = (
    (None, {'fields': ('role', 'bio')}),
)
